# -*- coding: utf-8 -*-
"""TerceiraAula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1taOTHVwFawNBBSSzWHoAKxBm9HVXkygz

# Condicionais

Principal forma de atribuir uma lógica ao nosso código

Só executa códigos que correspondem a condição especificada.

EX:


Se estiver quente
*   Tomar Sorvete
*   Vamos para a praia

Se tiver frio
*   Comer chocolate
*   Vamos ao cinema

# Condições 


*   Igualdade ==
*   Menor <
*   Maior >
*   Menor igual <=
*   IMaior igual >=
*   Diferente !=
"""

temperatura = 'frio'
if temperatura == 'quente':
  print('Vamos tomar sorvete de flocos!')
  print('Vamos para a praia')
else:
  print('Vamos comer chocolate')
  print('Vamos ao cinema')

numero = 20

if numero >= 20:
  print ('É um número grande')
else:
  print ('Não é um número grande')

nome = 'Maik'
if nome != 'Maik':
  print(f'Cada o Maik !')
elif nome == 'Maik':
  print('É o Maik')

# 1,3,5

numero = 5

if numero == 1:
  print ('Você ganhou')
elif numero == 3:
  print ('Você ganhou')
elif numero == 5:
  print ('Você ganhou')  
else:
  print ('Você perdeu!')

nome  = input ('Qual é seu primeiro nome? ')
sobrenome = input ('Qual é seu sobrenome? ')

if nome == 'Maik':
  if sobrenome == 'Costa':
    print('É o Maik Costa!')
  else:
    print('É outro Maik!')
else:
  print('Não é o Maik Costa')

# 1,3,5,7,9

numero = 7

if numero == 1:
  print ('Você ganhou')
elif numero == 3:
  print ('Você ganhou')
elif numero == 5:
  print ('Você ganhou')  
elif numero == 7:
  print ('Você ganhou')  
elif numero == 9:
  print ('Você ganhou')  
else:
  print ('Você perdeu!')

nome  = input ('Qual é seu primeiro nome? ')
sobrenome = input ('Qual é seu sobrenome? ')
idade = input('Qual é sua idade? ')
if nome == 'Maik':
  if sobrenome == 'Costa':
    if idade == 36:
      print('É o Maik Costa!')
    else:
      print('É outro Maik')
  else:
    print('É outro Maik!')
else:
  print('Não é o Maik Costa')

"""# Operadores Lógicos

Servem para utilizar condições compostas.

Uma condição E(**AND**) outra condição

*   Todos devem ser verdade

Uma condição OU (**OR**)outra condição

*   Ao menos um




"""

# 1,3,5

numero = 5

if numero == 1 or numero == 3 or numero == 5 or numero == 7 or numero == 9 :
  print ('Você ganhou')
else:
  print ('Você perdeu!')

nome  = input ('Qual é seu primeiro nome? ')
sobrenome = input ('Qual é seu sobrenome? ')
idade = input('Qual é sua idade? ')

if nome == 'Maik' and sobrenome == 'Costa' and idade == 36:
  print ("É o verdadeiro Maik!")
else:
  print("É outro Maik!")

# 1,3 ou 5
# Nome = Maik

nome = input('Qual é o seu nome? ')
numero = int (input('Qual é o seu número? '))


if nome.lower() == 'maik' and (numero == 1 or numero == 3 or numero == 5 ):
  print(f'O {nome} escolheu o número certo!')
else:
  print('Erro!')

numeros_aceitos = [1,3,5,7,9]

numero = int (input('Qual é o seu número? '))

if numero in numeros_aceitos:
  print('Você ganhou!')
else:
  print('Você perdeu!')

"""# Laços de repetição

Forma de evitar a repetição de código, executando uma ação repetidas vezes
"""

# Todos os numeros até 10 => 0...9!
# Mínimo é inclusivo => Existe
# Máximo é exclusivo => Não Existe

print(0)
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)

# for variavel in sequenca/lista:
for numero in range(10):
  print(numero)

# for variavel in sequencia:

# PARA CADA variavel NA MINHA sequencia :
  # executar uma repetição (código) => Iteração

# PARA CADA número NA MINHA sequencia de números até 10:
  # mostrar o numero

for numero  in range (10):
  print (f'O Número atual é {numero} ')

# 3 ~ [8]
for numero in range(3,9):
  print(numero)

# For com saltos a terceira posição "2" é a quantidade de saltos
for numero in range(3,16,2):
  print(numero)

resto_divisao = 9 % 2

resto_divisao

for numero in range(1,11):
  if numero % 2 == 0:
    print (f'O número {numero} é par!')
  if numero % 2 == 1:
    print (f'O número {numero} é impar!')

notas = [10,8,9,7,5]

soma = 0

for nota in notas:
  soma += nota
print (f'A Soma vale {soma}!')

media = soma / 3

print ('A media é', media)

soma

notas = [10,8,9,7,5]

quantidade = len(notas)
print('Quantidade de notas: ', quantidade)

soma = 0

for nota in notas:
  soma += nota
print (f'A Soma vale {soma}!')

media = soma / quantidade

print ('A media é', media)

notas = [10,7,5,9]

quantidade = len(notas)
soma = sum(notas)
media = soma / quantidade
print ('A media é', media)

def calcular_media(notas):
  quantidade = len(notas)
  soma = sum(notas)
  media = soma / quantidade
  print('O aluno tirou', media)
  verificar_aprovacao(media)

def verificar_aprovacao(media):
  if media >= 6:
    print('Aluno aprovado =)')
  else:
    print('Aluno reprovado =(')

    
maik= [10,8,9,7]
media = calcular_media(maik)

#Calculando IMC

def imc(peso, altura):
  altura_quadrada = altura ** 2
  meu_imc = peso / altura_quadrada
  return meu_imc

meu_imc = round(imc(94,1.87),2)

if meu_imc <= 18.4:
  print(f'Seu IMC é {meu_imc} classificado como: Magreza, grau de obesidade 0')
if meu_imc >= 18.5 and meu_imc <= 24.9:
  print(f'Seu IMC é {meu_imc} classificado como: Normal, grau de obesidade 0')
if meu_imc >= 25 and meu_imc <= 29.9:
  print(f'Seu IMC é {meu_imc} classificado como: SobrePeso, grau de obesidade I')
if meu_imc >= 30 and meu_imc <= 39.9:
  print(f'Seu IMC é {meu_imc} classificado como: Obesidade, grau de obesidade II')
if meu_imc >= 40:
  print(f'Seu IMC é {meu_imc} classificado como: Obesidade grave, grau de obesidade III')

